name: GiveEveryDamnAchievement
main: me.blha303.giveeverydamnachievement.Main
version: 3
commands:
  giveeverydamnachievement:
    description: Give the specified player every damn achievement
    usage: /giveeverydamnachievement <player>
    aliases: [geda]
permissions:
  giveeverydamnachievement.use:
    description: Lets the player use the command
    default: op
