name: GiveEveryDamnAchievement
main: me.blha303.giveeverydamnachievement.Main
version: 1
commands:
  giveeverydamnachievement:
    description: Give the specified player every damn achievement
    usage: /giveeverydamnachievement <player>
permissions:
  giveeverydamnachievement.use:
    description: Lets the player use the command
    default: op
